version: '3'

services:
  backend:
    image: jleadbetter/backend
    build:
        context: .
        dockerfile: ./backend/Dockerfile
        args:
          - APP_DIR=/opt/jleadbetter/app
    environment:
        - DJANGO_ALLOWED_HOSTS
        - DJANGO_DEBUG
        - DJANGO_SECRET_KEY
        - DJANGO_STATIC_ROOT
        - DJANGO_STATIC_URL
        - DJANGO_SUPERUSER_EMAIL
        - DJANGO_SUPERUSER_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - STATIC_SERVER
        - WEB_CONCURRENCY
    command: scripts/run.sh -b
    ports:
      - ${BACKEND_PORT}:8000
