version: '3'

services:
  backend:
    image: jleadbetter/backend
    environment:
        - DJANGO_ALLOWED_HOSTS
        - DJANGO_DEBUG
        - DJANGO_SECRET_KEY
        - DJANGO_STATIC_ROOT
        - DJANGO_STATIC_URL
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - STATIC_SERVER
        - WEB_CONCURRENCY=3
    command: gunicorn demo_backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - ${BACKEND_PORT}:8000
    # TODO: This is currently just for getting dev working; we should handle
    # this differently for prod
    volumes:
      - ./backend:/opt/jleadbetter/app
      - ./frontend/demo_backend_static:/opt/jleadbetter/static
    depends_on:
      - backend-db
      - backend-bootstrap

  backend-db:
    image: postgres:11.11
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - /var/lib/posgresql/data

  backend-bootstrap:
    image: jleadbetter/backend
    build:
        context: .
        dockerfile: ./backend/Dockerfile
        args:
          - APP_DIR=/opt/jleadbetter/app
    # TODO: create this as a script; include setting superuser
    command: python manage.py migrate --no-input && python manage.py collectstatic --no-input
    environment:
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - WEB_CONCURRENCY=3

  # This is only intended to be run for local testing and CircleCI; for prod
  # we'll build to S3
  frontend-dev:
    image: nginx:1.19.0
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/demo_frontend:/usr/share/nginx/html
      - ./frontend/demo_backend_static:/usr/share/nginx/html/static
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
