version: '3'

services:
  backend:
    image: jleadbetter/backend
    build:
        context: .
        dockerfile: ./backend/Dockerfile
    ports: 
      - ${BACKEND_PORT}:8000
    # TODO: This is currently just for getting dev working; we should handle
    # this differently for prod
    volumes:
      - ./backend:/var/app
    depends_on:
      - backend-db
  backend-db:
    image: postgres:11
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/posgresql/data
