###############################################################################
#                                                                             #
#  Setup only for prod servers.                                               #
#                                                                             #
#  Assumes the use of AWS RDS for the database and S3 for static files, so    #
#  there is no other setup than the backend needed. If you are doing local    #
#  development, use the docker-compose.override.yml.example to create the     #
#  additional machines needed to support the backend.                         #
#                                                                             #
###############################################################################

version: '3'

services:
  backend:
    image: jleadbetter/backend
    build:
        context: .
        dockerfile: ./backend/Dockerfile
        args:
          - APP_DIR=/opt/jleadbetter/app
    environment:
        - DJANGO_ALLOWED_HOSTS
        - DJANGO_DEBUG
        - DJANGO_FORCE_INSECURE
        - DJANGO_SECRET_KEY
        - DJANGO_STATIC_ROOT
        - DJANGO_STATIC_URL
        - DJANGO_SUPERUSER_EMAIL
        - DJANGO_SUPERUSER_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - STATIC_SERVER
        - WEB_CONCURRENCY
    command: scripts/run.sh -b
    ports:
      - ${BACKEND_PORT}:8000
