version: 2.1

default_python_image: &default_python_image
  image: circleci/python:3.8

orbs:
  python: circleci/python@1.3.4
  docker: circleci/docker@1.0.0
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-cli: circleci/aws-cli@2.0.0
  jq: circleci/jq@2.0.1
  slack: circleci/slack@4.2.0

###############################################################################

executors:
  default:
    resource_class: small
    working_directory: ~/repo
    docker:
      - <<: *default_python_image

  with-postgres:
    resource_class: medium
    working_directory: ~/repo
    docker:
      - <<: *default_python_image
        # TODO: add environment vars here
      - image: circleci/postgres:11
        # TODO: add environment vars here

###############################################################################


jobs:
  test-tox:
    executor: << parameters.executor >>
    description: Run tests specified for the tox test runner
    parameters:
      env:
        type: string
        description: The tox environment to run
      executor:
        type: executor
        default: default
    steps:
      - checkout

    # TODO: steps

  test-build-image:
    # Test the build configuration of the image

  build-and-push-image:
    # Build the project and push to AWS

  run-migrations:
    # Run django migrations against the database

  deploy-ecs:
    # Deploy the image


###############################################################################

workflows:
  github-pr-test:
    # This is intended to be run for pull requests
    jobs:
      - test-tox:
        name: flake8
        env: flake8
        filters:
          branches:
            ignore:
              - master

      - test-tox:
        name: isort
        env: isort
        filters:
          branches:
            ignore:
              - master

      - test-tox:
        name: tests
        env: tests
        filters:
          branches:
            ignore:
              - master

      - test-tox:
        name: deploy-check
        env: deploy-check
        filters:
          branches:
            ignore:
              - master

      - test-build-image:
        context: org-production
        filters:
          branches:
            ignore:
              - master

#####

  deploy:
    # Run for master branch, once a PR has been merged
      - test-tox:
        name: flake8
        env: flake8
        filters:
          branches:
            only:
              - master

      - test-tox:
        name: isort
        env: isort
        filters:
          branches:
            only:
              - master

      - test-tox:
        name: tests
        env: tests
        filters:
          branches:
            only:
              - master

      - test-tox:
        name: deploy-check
        env: deploy-check
        filters:
          branches:
            only:
              - master

      - build-and-push-image:
        context: org-prod
        requires:
          - flake8
          - isort
          - tests
          - deploy-check

      - run-migrations:
        name: migrations-prod
        region: eu-central-1
        tag: $CIRCLE_SHA1
        context: org-prod
        requires:
          - build-and-push-image

      - deploy-ecs:
        name: deploy-prod
        region: eu-central-1
        tag: $CIRCLE_SHA1
        context: org-production
        requires:
          - migrations-prod
