---

###############################################################################
#                                                                             #
#  Installs the setup for the backend server (Django)                         #
#                                                                             #
###############################################################################

- include_tasks: install_system_dependencies.yml
- include_tasks: setup_django.yml
