---

###############################################################################
#                                                                             #
#  Installs the setup for the backend server (Django)                         #
#                                                                             #
###############################################################################

- name: "Install project requirements"
  pip:
    chdir: "{{ app_dir }}"
    requirements: "requirements/server.txt"

# TODO: migrations
# TODO: fix that annoying message about not using /usr/bin/python3
