---

# nginx is used for serving django static files

- name: "Install nginx"
  shell:
    cmd: "apt-get install -y nginx"
  args:
    # Yes, ansible, we know we're not using the `apt` module
    warn: false

- name: "Copy over the nginx configuration file"
  copy:
    src: static_site.cfg
    dest: /etc/nginx/nginx.conf
