---

- name: "Install postgres dev libraries, for psycopg2"
  shell:
    cmd: "apt-get install -y {{ item }}"
  with_items:
    - libpq-dev
    - build-essential
  args:
    # Yes, ansible, we know we're not using the `apt` module
    warn: false

- name: "Upgrade pip"
  pip:
    name: pip
    state: latest

- name: "Install django project requirements"
  pip:
    chdir: "{{ app_dir }}"
    requirements: "requirements/server.txt"

